import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type ProductStatus = 'published' | 'draft' | 'archived';

export interface ProductVariant {
    id: string;
    size?: string;
    cut?: string;
    color?: string;
    sku: string;
    price?: number;
    stock: number;
}

export interface AdminProduct {
    id: string;
    titleEn: string;
    titleAr: string;
    slug: string;
    descriptionEn?: string;
    descriptionAr?: string;
    price: number;
    compareAtPrice?: number;
    category: string;
    categorySlug: string;
    images: string[];
    status: ProductStatus;
    variants: ProductVariant[];
    isCustom: boolean;
    isMadeToOrder: boolean;
    isBestSeller?: boolean;
    fabric?: string;
    color?: string;
    leadTimeDays?: number;
    createdAt: string;
    updatedAt: string;
}

const CDN = 'https://cdn.salla.sa/DGwjPD/';

function mkVariants(slug: string, sizes: string[], stock = 30): ProductVariant[] {
    return sizes.map(size => ({
        id: `${slug}-${size.toLowerCase()}`,
        size,
        sku: `${slug.toUpperCase()}-${size}`,
        stock,
    }));
}

const realProducts: AdminProduct[] = [
    {
        id: 'prod-abaya-aleid',
        titleAr: 'عباية العيد',
        titleEn: 'Eid Abaya',
        slug: 'abaya-aleid',
        descriptionAr: 'عباية فاخرة مصممة خصيصًا لمناسبة العيد بقماش راقٍ وتفاصيل أنيقة.',
        descriptionEn: 'A luxurious abaya designed especially for Eid with premium fabric and elegant details.',
        price: 179, compareAtPrice: 389,
        category: 'كولكشن العيد', categorySlug: 'eid-collection',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}a43d8450-672f-4d35-add3-5fd6a515a80c-370.47673750718x500-pmgpl4cmV6AxrNcrSurd2dzTJCrfT5XvRbnjL1hV.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-aleid', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-03-01T00:00:00Z', updatedAt: '2024-03-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-roz',
        titleAr: 'عباية روز',
        titleEn: 'Rose Abaya',
        slug: 'abaya-roz',
        descriptionAr: 'عباية من كولكشن العيد بتصميم ورد أنيق ولمسات رقيقة.',
        descriptionEn: 'Eid collection abaya with an elegant rose design and delicate touches.',
        price: 179, compareAtPrice: 399,
        category: 'كولكشن العيد', categorySlug: 'eid-collection',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}76514640-fdf8-4d03-8afd-4b00cb05c6f1-382.46205733558x500-Ei5Iq4Z2tn9xpu4zKPAsDN3BfcYBuxxeH5eOlxjJ.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-roz', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-03-02T00:00:00Z', updatedAt: '2024-03-02T00:00:00Z',
    },
    {
        id: 'prod-abaya-february',
        titleAr: 'عباية فبراير',
        titleEn: 'February Abaya',
        slug: 'abaya-february',
        descriptionAr: 'إصدار فبراير من كولكشن العيد، تصميم راقٍ يجمع الأصالة والعصرية.',
        descriptionEn: 'February Eid collection edition — a refined design blending heritage and modernity.',
        price: 189, compareAtPrice: 450,
        category: 'كولكشن العيد', categorySlug: 'eid-collection',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}1daf73a9-a212-4d0f-b053-e4d10927bdb1-367.82354849173x500-12O5eHt28G5YMZ1xjUg0Nwu73oxVlszq7D9liEVP.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-february', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-02-01T00:00:00Z', updatedAt: '2024-02-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-mira',
        titleAr: 'عباية ميرا',
        titleEn: 'Mira Abaya',
        slug: 'abaya-mira',
        descriptionAr: 'عباية ميرا الكلاسيكية بقصة أنيقة ومريحة.',
        descriptionEn: 'Classic Mira abaya with an elegant and comfortable cut.',
        price: 159, compareAtPrice: 350,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}44275502-3ac1-4dd7-9881-168458ab6dd5-379.13741223671x500-l5XaClLEQmwxdLpF9PrKX3po1BDs87MTBOcJJjps.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-mira', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-15T00:00:00Z', updatedAt: '2024-01-15T00:00:00Z',
    },
    {
        id: 'prod-niqab-family-bundle',
        titleAr: 'بكج العائلة - 5 نقابات',
        titleEn: 'Family Bundle - 5 Niqabs',
        slug: 'niqab-family-bundle',
        descriptionAr: 'بكج اقتصادي يحتوي على 5 نقابات عالية الجودة للعائلة.',
        descriptionEn: 'Value pack with 5 high-quality niqabs for the whole family.',
        price: 59, compareAtPrice: 95,
        category: 'نقاب', categorySlug: 'niqab',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}295a0256-9d01-4e36-a1d5-a491abd1a413-338.03986710963x500-Q0p44Jk55KPTN3kIhYO7amxXGuY8TPFrzSBA4QVn.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('niqab-family-bundle', ['OS']),
        createdAt: '2024-01-10T00:00:00Z', updatedAt: '2024-01-10T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-dantel',
        titleAr: 'عباية كرز دانتيل',
        titleEn: 'Kraz Lace Abaya',
        slug: 'abaya-kraz-dantel',
        descriptionAr: 'عباية كرز مع تطريز دانتيل فاخر على الأكمام والطوق، من أكثر العبايات مبيعًا.',
        descriptionEn: 'Kraz abaya with luxurious lace embroidery on sleeves and collar — our best seller.',
        price: 169, compareAtPrice: 299,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}ec99a87b-4b28-4082-8188-3230a57684ce-406.94006309148x500-gTVdE0Za8jl4ibuGLhTyEeloMG6QfXSXXV11sQY2.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-dantel', ['S', 'M', 'L', 'XL'], 5),
        createdAt: '2023-12-01T00:00:00Z', updatedAt: '2024-02-15T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-ward',
        titleAr: 'عباية كرز ورد',
        titleEn: 'Kraz Rose Abaya',
        slug: 'abaya-kraz-ward',
        descriptionAr: 'عباية كرز بنقشة ورد رقيقة، إصدار كولكشن العيد.',
        descriptionEn: 'Kraz abaya with a delicate rose pattern from the Eid collection.',
        price: 159, compareAtPrice: 290,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}362e1531-582c-4aff-81ad-e2f414d8eace-387.38738738739x500-1ZKmxvkaduArxse7WgU7c0afEbHCBqnJiwIzFPHt.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-ward', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-02-20T00:00:00Z', updatedAt: '2024-02-20T00:00:00Z',
    },
    {
        id: 'prod-abaya-aneqa-dantel',
        titleAr: 'عباية الأنيقة - دانتيل',
        titleEn: 'Al-Aneqa Lace Abaya',
        slug: 'abaya-aneqa-dantel',
        descriptionAr: 'عباية الأنيقة بتفاصيل دانتيل فاخرة، من أكثر التصاميم مبيعًا.',
        descriptionEn: 'Al-Aneqa abaya with exquisite lace detailing — a top-selling design.',
        price: 179, compareAtPrice: 320,
        category: 'دانتيل', categorySlug: 'dantel',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}a50cb699-82cb-401b-a755-b5d1de0e8c22-381.77940280317x500-gqZJcsKvQcHhrqEknzBolbiwp6uWQOvOx0HsMPwW.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-aneqa-dantel', ['S', 'M', 'L', 'XL'], 8),
        createdAt: '2024-01-05T00:00:00Z', updatedAt: '2024-02-10T00:00:00Z',
    },
    {
        id: 'prod-abaya-july-dantel',
        titleAr: 'عباية يوليو - دانتيل',
        titleEn: 'July Lace Abaya',
        slug: 'abaya-july-dantel',
        descriptionAr: 'عباية يوليو بتطريز دانتيل أنيق على الأكمام والطوق.',
        descriptionEn: 'July abaya with elegant lace embroidery on sleeves and collar.',
        price: 179, compareAtPrice: 350,
        category: 'دانتيل', categorySlug: 'dantel',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}cd2dbf1c-e62c-4223-9a4c-c7dfce6aaa9c-416.12903225806x500-WJtfCRYn85TDrb0p1ynN2ILVVkHnffdsXc9WoOLJ.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-july-dantel', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-20T00:00:00Z', updatedAt: '2024-01-20T00:00:00Z',
    },
    {
        id: 'prod-abaya-ward',
        titleAr: 'عباية ورد',
        titleEn: 'Ward Abaya',
        slug: 'abaya-ward',
        descriptionAr: 'عباية ورد من كولكشن العيد بتصميم رومانسي راقٍ.',
        descriptionEn: 'Ward Abaya from the Eid collection with a romantic, refined design.',
        price: 169, compareAtPrice: 370,
        category: 'كولكشن العيد', categorySlug: 'eid-collection',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}b9e7de98-e044-4a0e-9d42-117e1af5d1e2-343.53226295062x500-Lg8AJCRWbv6BU5WEPpq8rRvtzDY082iDuJGVeKNe.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-ward', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-02-10T00:00:00Z', updatedAt: '2024-02-10T00:00:00Z',
    },
    {
        id: 'prod-abaya-mars-ward',
        titleAr: 'عباية مارس ورد',
        titleEn: 'Mars Rose Abaya',
        slug: 'abaya-mars-ward',
        descriptionAr: 'إصدار مارس من تصميم ورد الأنيق، ضمن كولكشن العيد.',
        descriptionEn: 'March edition of the elegant rose design from the Eid collection.',
        price: 159, compareAtPrice: 290,
        category: 'كولكشن العيد', categorySlug: 'eid-collection',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}92bbf780-0f21-42e9-86b6-aa65526a50d8-390.32655576094x500-s2PmHapIBPh4Dfl9v7R8NjIntiIxuCnHxRvsS5RT.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-mars-ward', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-03-05T00:00:00Z', updatedAt: '2024-03-05T00:00:00Z',
    },
    {
        id: 'prod-niqab',
        titleAr: 'نقاب',
        titleEn: 'Niqab',
        slug: 'niqab',
        descriptionAr: 'نقاب فاخر من قماش ناعم عالي الجودة، مريح للارتداء اليومي.',
        descriptionEn: 'Premium niqab from soft, high-quality fabric — comfortable for daily wear.',
        price: 19, compareAtPrice: 30,
        category: 'نقاب', categorySlug: 'niqab',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}d2a76b00-4964-4afd-92cb-7bfe9c084e0f-379.57446808511x500-Q9Ak4IvksjLAJk5aXmK7xkKw3qhfAzonzT1yVbPq.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('niqab', ['OS']),
        createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-black',
        titleAr: 'عباية كرز أسود',
        titleEn: 'Kraz Black Abaya',
        slug: 'abaya-kraz-black',
        descriptionAr: 'عباية كرز الكلاسيكية باللون الأسود، الأكثر مبيعًا في المتجر.',
        descriptionEn: "Classic black Kraz abaya — the store's all-time best seller.",
        price: 159, compareAtPrice: 280,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}a1ba197c-5a0b-463f-b801-3463a3b1906e-410x500-HN5TuleeuqGuLerFC34JzItYDxQ8saaA7sUiIthY.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-black', ['S', 'M', 'L', 'XL'], 15),
        createdAt: '2023-11-01T00:00:00Z', updatedAt: '2024-01-20T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-brown',
        titleAr: 'عباية كرز بني',
        titleEn: 'Kraz Brown Abaya',
        slug: 'abaya-kraz-brown',
        descriptionAr: 'عباية كرز باللون البني الراقي، خيار مميز لكل المناسبات.',
        descriptionEn: 'Kraz abaya in elegant brown — a distinguished choice for all occasions.',
        price: 159, compareAtPrice: 280,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'brown',
        images: [`${CDN}aa312f46-3dbb-463f-a6a4-24af98cb827d-417.47572815534x500-J0zuVPtQ2UdnANsKSJHtIdBLo7seX7uzEi8I4NpP.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-brown', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-11-05T00:00:00Z', updatedAt: '2024-01-10T00:00:00Z',
    },
    {
        id: 'prod-abaya-rahaf-jokh',
        titleAr: 'عباية رهف جوخ',
        titleEn: 'Rahaf Wool Abaya',
        slug: 'abaya-rahaf-jokh',
        descriptionAr: 'عباية رهف من قماش الجوخ الشتوي الفاخر، دافئة وأنيقة.',
        descriptionEn: 'Rahaf abaya in luxurious winter wool — warm and elegant.',
        price: 159, compareAtPrice: 390,
        category: 'تشكيلة الشتاء', categorySlug: 'winter',
        fabric: 'wool', color: 'black',
        images: [`${CDN}8133fab2-d10f-49e5-aaa8-531a4ed19db4-500x500-YU29F4BTqmWRWz1YgLtkClmBMUCF1rgR8haFauRW.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-rahaf-jokh', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-10-15T00:00:00Z', updatedAt: '2023-11-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-december',
        titleAr: 'عباية ديسمبر',
        titleEn: 'December Abaya',
        slug: 'abaya-december',
        descriptionAr: 'إصدار ديسمبر الحصري، تصميم شتوي أنيق من الأكثر مبيعًا.',
        descriptionEn: 'Exclusive December edition — an elegant winter design and a bestseller.',
        price: 159, compareAtPrice: 330,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}50cea685-dfe8-42f1-9f40-3cd7f830afb4-389.85148514851x500-UI9yc17H9oPbJxvoCajAzF0TfAcAhzf2h16JoXbV.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-december', ['S', 'M', 'L', 'XL'], 12),
        createdAt: '2023-12-01T00:00:00Z', updatedAt: '2024-01-05T00:00:00Z',
    },
    {
        id: 'prod-abaya-mars-jokh-sleeves',
        titleAr: 'عباية مارس أكمام جوخ',
        titleEn: 'Mars Wool Sleeves Abaya',
        slug: 'abaya-mars-jokh-sleeves',
        descriptionAr: 'عباية مارس بأكمام من الجوخ الشتوي الفاخر، عرض خاص لفترة محدودة.',
        descriptionEn: 'Mars abaya with luxurious winter wool sleeves — special limited offer.',
        price: 159, compareAtPrice: 290,
        category: 'تشكيلة الشتاء', categorySlug: 'winter',
        fabric: 'wool', color: 'black',
        images: [`${CDN}43b14af9-f7b3-427b-8df1-38247a39a2bb-365.85365853659x500-nU8MyCl7PkNWoWpUdSthd61wUZUTRNYhnVCaFHHc.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-mars-jokh-sleeves', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-03-01T00:00:00Z', updatedAt: '2024-03-01T00:00:00Z',
    },
    {
        id: 'prod-kraz-black-jokh',
        titleAr: 'كرز أسود جوخ',
        titleEn: 'Kraz Black Wool',
        slug: 'kraz-black-jokh',
        descriptionAr: 'عباية كرز باللون الأسود من قماش الجوخ الشتوي، عرض ٢٤ ساعة فقط.',
        descriptionEn: 'Kraz abaya in black wool fabric — 24-hour flash offer.',
        price: 159, compareAtPrice: 300,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'wool', color: 'black',
        images: [`${CDN}dbc353f9-d830-4840-aa70-82b16efac223-379.85865724382x500-xL5rU56nae4GpvtKXEzqGdvPzh9MDTdRO0AdtrS0.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('kraz-black-jokh', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-11-20T00:00:00Z', updatedAt: '2023-11-20T00:00:00Z',
    },
    {
        id: 'prod-abaya-mars-black',
        titleAr: 'عباية مارس أسود',
        titleEn: 'Mars Black Abaya',
        slug: 'abaya-mars-black',
        descriptionAr: 'عباية مارس الأسود الكلاسيكية، من الأكثر مبيعًا بتصميم عصري أنيق.',
        descriptionEn: 'Classic Mars black abaya — a bestseller with a modern elegant design.',
        price: 159, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}f9057b49-ec06-40fe-ae59-4b0ae02c1c19-369.2714453584x500-wytsxECY4TpiZ8jeB370gBy32lswuxn9IQeHTScr.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-mars-black', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-10-01T00:00:00Z', updatedAt: '2024-02-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-k10',
        titleAr: 'عباية K10',
        titleEn: 'K10 Abaya',
        slug: 'abaya-k10',
        descriptionAr: 'التصميم K10 الحصري بقصة فريدة وتفاصيل دقيقة.',
        descriptionEn: 'Exclusive K10 design with a unique cut and fine details.',
        price: 169, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}7d824307-6039-4edb-8458-97ff429b4a3d-396.19164619165x500-V91dvTtQxIdxkmwoMsgCc2WLzOcyhvBfYypwuNPg.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-k10', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-25T00:00:00Z', updatedAt: '2024-01-25T00:00:00Z',
    },
    {
        id: 'prod-abaya-shahd',
        titleAr: 'عباية شهد',
        titleEn: 'Shahd Abaya',
        slug: 'abaya-shahd',
        descriptionAr: 'عباية شهد الجديدة بتصميم معاصر وقماش فاخر.',
        descriptionEn: 'New Shahd abaya with a contemporary design and luxurious fabric.',
        price: 179, compareAtPrice: 359,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}05d71b26-275e-4320-9947-b3fb3c73e74c-444.05286343612x500-PGXlWjkGmUx1LoEJFGDrzkoVF5KFmwydBKRLwRCX.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-shahd', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-02-28T00:00:00Z', updatedAt: '2024-02-28T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-navy',
        titleAr: 'عباية كرز كحلي',
        titleEn: 'Kraz Navy Abaya',
        slug: 'abaya-kraz-navy',
        descriptionAr: 'عباية كرز باللون الكحلي الراقي، تناسب جميع المناسبات.',
        descriptionEn: 'Kraz abaya in elegant navy — suitable for all occasions.',
        price: 159, compareAtPrice: 280,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'navy',
        images: [`${CDN}d711204c-e629-4e0d-8d21-b970ec705dca-407.99739921977x500-AiCNtIydM93qkXuKYTgzIU5uOjS8Jjht6oC9NEp2.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-navy', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-18T00:00:00Z', updatedAt: '2024-01-18T00:00:00Z',
    },
    {
        id: 'prod-abaya-november',
        titleAr: 'عباية نوفمبر',
        titleEn: 'November Abaya',
        slug: 'abaya-november',
        descriptionAr: 'إصدار نوفمبر الشتوي، تصميم جديد بقماش دافئ وأنيق.',
        descriptionEn: 'New November winter edition — warm and elegant fabric.',
        price: 159, compareAtPrice: 320,
        category: 'تشكيلة الشتاء', categorySlug: 'winter',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}2206b6b7-cda1-48ab-bfc5-3d8d2e8c0a71-378.26086956522x500-e4Xo1FC6x4d3lZaCcuH3XjUg2gBvhHbU2U7PNmh0.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-november', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-11-01T00:00:00Z', updatedAt: '2023-11-01T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-beige',
        titleAr: 'عباية كرز بيج',
        titleEn: 'Kraz Beige Abaya',
        slug: 'abaya-kraz-beige',
        descriptionAr: 'عباية كرز باللون البيج العصري، أناقة تناسب كل يوم.',
        descriptionEn: 'Kraz abaya in modern beige — everyday elegance.',
        price: 159, compareAtPrice: 280,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'beige',
        images: [`${CDN}576402a1-740a-4799-8df8-b5568af4c99f-375.87412587413x500-nmIJSN9UlZrALJ7OTpxWy937KktGtDpTLZQxDcag.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-beige', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-12T00:00:00Z', updatedAt: '2024-01-12T00:00:00Z',
    },
    {
        id: 'prod-abaya-ruf',
        titleAr: 'عباية روف',
        titleEn: 'Ruf Abaya',
        slug: 'abaya-ruf',
        descriptionAr: 'عباية روف بقصة مميزة وتفاصيل راقية.',
        descriptionEn: 'Ruf abaya with a distinctive cut and refined details.',
        price: 169, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}2cdb7738-c9d7-4065-9500-91dfaf326503-382.33550681683x500-eZY1b9ytLMawMByHzGOZQpSVlr4wuikImeYcL6o7.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-ruf', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-02-05T00:00:00Z', updatedAt: '2024-02-05T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-burgundy',
        titleAr: 'عباية كرز عنابي',
        titleEn: 'Kraz Burgundy Abaya',
        slug: 'abaya-kraz-burgundy',
        descriptionAr: 'عباية كرز باللون العنابي الجذاب، تصميم راقٍ لكل المناسبات.',
        descriptionEn: 'Kraz abaya in rich burgundy — an elegant design for all occasions.',
        price: 159, compareAtPrice: 280,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'crepe', color: 'burgundy',
        images: [`${CDN}e0f87d0e-ad50-4128-b64e-17da459202ca-380.08249852681x500-UiJL4MTNv9lyndxFAvFVMrutI9FoGygTB8Jv53oE.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-burgundy', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-22T00:00:00Z', updatedAt: '2024-01-22T00:00:00Z',
    },
    {
        id: 'prod-aneqa-navy',
        titleAr: 'الأنيقة - كحلي',
        titleEn: 'Al-Aneqa Navy',
        slug: 'aneqa-navy',
        descriptionAr: 'عباية الأنيقة باللون الكحلي الراقي، تصميم عصري مميز.',
        descriptionEn: 'Al-Aneqa abaya in elegant navy — a distinctive modern design.',
        price: 159, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'navy',
        images: [`${CDN}d6a4c76d-c7b5-40b0-aec3-9313297847bd-392.57455873402x500-Wh3S3FUrL5viaU29xEMtO4vyXDk0x2wZEhHjoXgM.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('aneqa-navy', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-28T00:00:00Z', updatedAt: '2024-01-28T00:00:00Z',
    },
    {
        id: 'prod-aneqa-black',
        titleAr: 'الأنيقة - أسود',
        titleEn: 'Al-Aneqa Black',
        slug: 'aneqa-black',
        descriptionAr: 'عباية الأنيقة باللون الأسود الكلاسيكي، أناقة لا تخطئها العين.',
        descriptionEn: 'Al-Aneqa abaya in classic black — timeless elegance.',
        price: 159, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'black',
        images: [`${CDN}9d7036a8-248c-4b0c-b67a-8d4c69f2b4e7-372.40184757506x500-QAId8HLURT0yVhjDbOLwTmpc3i6CAQ9EPcRt00lR.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('aneqa-black', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-30T00:00:00Z', updatedAt: '2024-01-30T00:00:00Z',
    },
    {
        id: 'prod-aneqa-grey',
        titleAr: 'الأنيقة - رمادي',
        titleEn: 'Al-Aneqa Grey',
        slug: 'aneqa-grey',
        descriptionAr: 'عباية الأنيقة باللون الرمادي العصري، من الأكثر مبيعًا.',
        descriptionEn: 'Al-Aneqa abaya in modern grey — a bestselling shade.',
        price: 159, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'grey',
        images: [`${CDN}6fe9b4e3-e0a6-4470-8d43-544c4c67bd28-379.85865724382x500-Z6usENffs3723gIoYSl9FvUald7WMqxVL0FjJgVD.jpg`],
        status: 'published', isBestSeller: true, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('aneqa-grey', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-01-08T00:00:00Z', updatedAt: '2024-02-20T00:00:00Z',
    },
    {
        id: 'prod-abaya-kraz-dantel-velvet-winter',
        titleAr: 'عباية كرز دانتيل شتوية مخمل',
        titleEn: 'Kraz Lace Velvet Winter Abaya',
        slug: 'abaya-kraz-dantel-velvet-winter',
        descriptionAr: 'عباية كرز شتوية بتطريز دانتيل فاخر وقماش مخمل دافئ، إصدار شتوي حصري.',
        descriptionEn: 'Kraz winter abaya with luxurious lace embroidery and warm velvet fabric — exclusive winter edition.',
        price: 179, compareAtPrice: 320,
        category: 'عباية كرز', categorySlug: 'kraz-abaya',
        fabric: 'velvet', color: 'black',
        images: [`${CDN}b7f566e4-5829-4fc8-973b-af831195ccba-375x500-YGsUKDLvXYTg9HcSzOdwbylVWv97sfUVOIQL8l5b.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-kraz-dantel-velvet-winter', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-12-15T00:00:00Z', updatedAt: '2023-12-15T00:00:00Z',
    },
    {
        id: 'prod-abaya-velvet-sleeves',
        titleAr: 'عباية أكمام مخمل',
        titleEn: 'Velvet Sleeves Abaya',
        slug: 'abaya-velvet-sleeves',
        descriptionAr: 'عباية شتوية بأكمام مخمل ناعمة، دفء وأناقة في آنٍ واحد.',
        descriptionEn: 'Winter abaya with soft velvet sleeves — warmth and elegance combined.',
        price: 165, compareAtPrice: 280,
        category: 'تشكيلة الشتاء', categorySlug: 'winter',
        fabric: 'velvet', color: 'black',
        images: [`${CDN}7a850e39-e117-44b3-8cde-d41f47f097d9-394.9785670545x500-Cre4MlYmew5ssN1gMbliaPGsZoHn6dMRbbdJuFJ7.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-velvet-sleeves', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-12-10T00:00:00Z', updatedAt: '2023-12-10T00:00:00Z',
    },
    {
        id: 'prod-chamois-navy-k6',
        titleAr: 'شامواه كحلي K6',
        titleEn: 'Chamois Navy K6',
        slug: 'chamois-navy-k6',
        descriptionAr: 'عباية شامواه K6 باللون الكحلي من تشكيلة الشتاء، ناعمة ودافئة.',
        descriptionEn: 'Chamois K6 in navy from the winter collection — soft and warm.',
        price: 159, compareAtPrice: 290,
        category: 'تشكيلة الشتاء', categorySlug: 'winter',
        fabric: 'chamois', color: 'navy',
        images: [`${CDN}74c4035e-0761-4c58-8632-e09cf04b0e1c-365.60693641619x500-2zoly4F9c4MRNyeOOy8IoPo4LkW8gGYRMrv0gbxy.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('chamois-navy-k6', ['S', 'M', 'L', 'XL']),
        createdAt: '2023-11-15T00:00:00Z', updatedAt: '2023-11-15T00:00:00Z',
    },
    {
        id: 'prod-abaya-mars-brown',
        titleAr: 'عباية مارس بني',
        titleEn: 'Mars Brown Abaya',
        slug: 'abaya-mars-brown',
        descriptionAr: 'عباية مارس باللون البني الراقي، تصميم أنيق مناسب لكل المناسبات.',
        descriptionEn: 'Mars abaya in elegant brown — suitable for all occasions.',
        price: 159, compareAtPrice: 280,
        category: 'عبايات', categorySlug: 'all-abayas',
        fabric: 'crepe', color: 'brown',
        images: [`${CDN}ca124ba5-391e-4c6b-9567-9bf253bcd095-413.54372123603x500-ROqU7Zu1ighhyPLuPgRlcIsy7mCpxN7Z3i5uI57A.jpg`],
        status: 'published', isBestSeller: false, isCustom: false, isMadeToOrder: false,
        variants: mkVariants('abaya-mars-brown', ['S', 'M', 'L', 'XL']),
        createdAt: '2024-03-10T00:00:00Z', updatedAt: '2024-03-10T00:00:00Z',
    },
];

interface AdminProductsStore {
    products: AdminProduct[];
    addProduct: (product: Omit<AdminProduct, 'id' | 'createdAt' | 'updatedAt'>) => void;
    updateProduct: (id: string, product: Partial<Omit<AdminProduct, 'id'>>) => void;
    deleteProduct: (id: string) => void;
    updateProductStatus: (id: string, status: ProductStatus) => void;
}

export const useAdminProducts = create<AdminProductsStore>()(
    persist(
        (set) => ({
            products: realProducts,
            addProduct: (data) => set((state) => {
                const newProduct: AdminProduct = {
                    ...data,
                    id: `prod-${Date.now()}`,
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString()
                };
                return { products: [newProduct, ...state.products] };
            }),
            updateProduct: (id, data) => set((state) => ({
                products: state.products.map(p =>
                    p.id === id ? { ...p, ...data, updatedAt: new Date().toISOString() } : p
                )
            })),
            deleteProduct: (id) => set((state) => ({
                products: state.products.filter(p => p.id !== id)
            })),
            updateProductStatus: (id, status) => set((state) => ({
                products: state.products.map(p =>
                    p.id === id ? { ...p, status, updatedAt: new Date().toISOString() } : p
                )
            }))
        }),
        {
            name: 'admin-products-storage',
            version: 2, // bump version to reset stale localStorage cache
        }
    )
);
